import type { BookListProps } from "@/components/BookList/BookList.types";

export const dummySearchResults: BookListProps[] = [
  {
    readingState: "before",
    title: "불편한 편의점",
    author: "김호연",
    publisher: "나무옆의자",
    publicYear: "2021",
    totalPages: 150,
    tags: ["소설", "감동", "베스트셀러"],
    level: 1,
    country: "한국소설",
    genre: "소설",
  },

  {
    readingState: "before",
    title: "해리포터와 마법사의 돌",
    author: "J.K. 롤링",
    publisher: "문학수첩",
    publicYear: "2019",
    totalPages: 240,
    tags: ["판타지", "영화원작", "영미소설"],
    level: 2,
    country: "영미소설",
    genre: "장르",
  },

  {
    readingState: "before",
    title: "이방인",
    author: "알베르 카뮈",
    publisher: "민음사",
    publicYear: "2011",
    totalPages: 280,
    tags: ["고전", "프랑스문학", "철학"],
    level: 3,
    country: "프랑스소설",
    genre: "인문",
  },

  {
    readingState: "before",
    title: "달러구트 꿈 백화점",
    author: "이미예",
    publisher: "팩토리나인",
    publicYear: "2020",
    totalPages: 300,
    tags: ["판타지", "K-소설", "힐링"],
    level: 1,
    country: "한국소설",
    genre: "소설",
  },

  {
    readingState: "before",
    title: "용의자 X의 헌신",
    author: "히가시노 게이고",
    publisher: "재인",
    publicYear: "2017",
    totalPages: 220,
    tags: ["추리", "미스터리", "일본소설"],
    level: 1,
    country: "일본소설",
    genre: "장르",
  },

  {
    readingState: "before",
    title: "데미안",
    author: "헤르만 헤세",
    publisher: "민음사",
    publicYear: "2009",
    totalPages: 180,
    tags: ["성장", "고전", "독일문학"],
    level: 2,
    country: "독일소설",
    genre: "인문",
  },

  {
    readingState: "before",
    title: "삼체",
    author: "류츠신",
    publisher: "자음과모음",
    publicYear: "2013",
    totalPages: 450,
    tags: ["SF", "과학", "중국소설"],
    level: 3,
    country: "중국소설",
    genre: "장르",
  },
];
